name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 打包发布到 gh-pages
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install deps & build project
        run : yarn --frozen-lockfile && yarn build

      - name: deploy github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          
      
      
      
      
      
      
      
      
